### ISSUE TITLE
Support for wildcard domains?

### ISSUE THREAD

**Issue by gregor-hh** [fire1ce/DDNS-Cloudflare-PowerShell#1]
Hello,
at first Thank you very much for this script. Great.

Question:
Is it possible that you add the ability to update a wildcard domain? *.example.com ?

Best regards

**Comment by fire1ce** [comment]
@gregor-hh "*.example.com" means "every subdomain". 
It's counter intuitive for DDNS script. Just set a Cname for the DDNS subtomain you are using.
