### ISSUE TITLE
"Error! Update Failed"

### ISSUE THREAD

**Issue by MrSupaBeast** [fire1ce/DDNS-Cloudflare-PowerShell#5]
Something isn't working properly. I have added DNS record to be updated, Zone ID and API token. The log file states last run time and correct external IP. 

Last entry however is "Trying to update...
Error! Update Failed
"

**Comment by fire1ce** [comment]
run the script manually via powershell. it will print a system error you your configuration failed

**Comment by MrSupaBeast** [comment]
I will try this later today. When I initially set this up, I ran the script without errors. It wasn’t until it actually had to update the dns records it failed. Yesterday I setup a temporary solution using ddclient on on of my vm’s. Ddclient also had trouble updating dns records using a regular api key. It wasn’t until I used the global api key it started working. Perhaps It could be something related to the powershell script issue I had?

**Comment by fire1ce** [comment]
My script is intended to be used ONLY with proper API Token. My guess is related to your Token permissions. Those scrips are runing at my end wihout issues.

**Comment by fire1ce** [comment]
I've updated the Redme file with proper creation of the API Token.
https://github.com/fire1ce/DDNS-Cloudflare-PowerShell#creating-cloudflare-api-token

**Comment by MrSupaBeast** [comment]
Just like you said, it was a token permission issue. I had the token set to edit and I added read as well. Seeing now that you only mention read, I assume edit isn't needed?
"Grant the token the following permissions:

    Zone - DNS - Read
"

**Comment by fire1ce** [comment]
it should be edit. i’ll fix it later

**Comment by fire1ce** [comment]
> Just like you said, it was a token permission issue. I had the token set to edit and I added read as well. Seeing now that you only mention read, I assume edit isn't needed? "Grant the token the following permissions:
> 
> ```
> Zone - DNS - Read
> ```

I've fixed the README. 
Closeing the issue.
